import Head from "next/head";

// mui components
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="sm">
          this text is outside a box
          <Box sx={{ my: 4, border: '1px dashed grey' }}>
            this text is inside a box
          </Box>
        </Container>

      </main>
    </>
  );
}
